# Generated by Django 3.0.5 on 2020-05-06 05:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap_laboratorium', models.CharField(max_length=100)),
                ('akronim_laboratorium', models.CharField(max_length=100)),
                ('alamat_lengkap', models.CharField(max_length=100)),
                ('kab_kota', models.CharField(max_length=50)),
                ('kode_pos', models.CharField(max_length=10)),
                ('posisi_lintang', models.CharField(max_length=100)),
                ('posisi_bujur', models.CharField(max_length=100)),
                ('nomor_telepon', models.CharField(max_length=20)),
                ('fax', models.CharField(max_length=20)),
                ('website', models.CharField(max_length=50)),
                ('laboratorium_id', models.CharField(max_length=50)),
                ('afiliasi_laboratorium', models.CharField(blank=True, choices=[('Publik/Pemerintah', 'Publik/Pemerintah'), ('Privat', 'Privat'), ('Universitas', 'Universitas'), ('Industri', 'Industri'), ('Lainnya', 'Lainnya')], max_length=30, null=True)),
                ('administrasi_laboratorium', models.CharField(blank=True, choices=[('Provinsi', 'Provinsi'), ('Nasional', 'Nasional'), ('Regional', 'Regional'), ('Internasional', 'Internasional'), ('N/A', 'N/A')], max_length=30, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
