# Generated by Django 3.0.5 on 2020-05-07 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_aktivitas_laboratorium'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='negara',
            field=models.CharField(blank=True, choices=[('Indonesia', 'Indonesia'), ('Malaysia', 'Malaysia'), ('Thailand', 'Thailand'), ('Kamboja', 'Kamboja'), ('Laos', 'Laos'), ('Vietnam', 'Vietnam'), ('Brunei', 'Brunei'), ('Singapura', 'Singapura')], max_length=30, null=True),
        ),
    ]
