# Generated by Django 3.0.5 on 2020-05-13 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_negara'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='laboratorium_id',
        ),
    ]
