# Generated by Django 3.0.5 on 2020-05-14 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200514_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='provinsi_selain_indo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
