# Generated by Django 3.0.5 on 2020-05-19 04:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireSatu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai_satu', models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1)], default=4)),
                ('keterangan_satu', models.TextField()),
                ('na_satu', models.PositiveSmallIntegerField(choices=[(True, 'Yes'), (False, 'No')], default=True)),
                ('nilai_dua', models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1)], default=4)),
                ('keterangan_dua', models.TextField()),
                ('na_dua', models.PositiveSmallIntegerField(choices=[(True, 'Yes'), (False, 'No')], default=True)),
                ('nilai_tiga', models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1)], default=4)),
                ('keterangan_tiga', models.TextField()),
                ('na_tiga', models.PositiveSmallIntegerField(choices=[(True, 'Yes'), (False, 'No')], default=True)),
                ('nilai_empat', models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1)], default=4)),
                ('keterangan_empat', models.TextField()),
                ('na_empat', models.PositiveSmallIntegerField(choices=[(True, 'Yes'), (False, 'No')], default=True)),
                ('nilai_lima', models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1)], default=4)),
                ('keterangan_lima', models.TextField()),
                ('na_lima', models.PositiveSmallIntegerField(choices=[(True, 'Yes'), (False, 'No')], default=True)),
                ('nilai_enam', models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1)], default=4)),
                ('keterangan_enam', models.TextField()),
                ('na_enam', models.PositiveSmallIntegerField(choices=[(True, 'Yes'), (False, 'No')], default=True)),
                ('nilai_tujuh', models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1)], default=4)),
                ('keterangan_tujuh', models.TextField()),
                ('na_tujuh', models.PositiveSmallIntegerField(choices=[(True, 'Yes'), (False, 'No')], default=True)),
                ('nilai_delapan', models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1)], default=4)),
                ('keterangan_delapan', models.TextField()),
                ('na_delapan', models.PositiveSmallIntegerField(choices=[(True, 'Yes'), (False, 'No')], default=True)),
                ('nilai_sembilan', models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1)], default=4)),
                ('keterangan_sembilan', models.TextField()),
                ('na_sembilan', models.PositiveSmallIntegerField(choices=[(True, 'Yes'), (False, 'No')], default=True)),
                ('nilai_sepuluh', models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1)], default=4)),
                ('keterangan_sepuluh', models.TextField()),
                ('na_sepuluh', models.PositiveSmallIntegerField(choices=[(True, 'Yes'), (False, 'No')], default=True)),
                ('nilai_sebelas', models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1)], default=4)),
                ('keterangan_sebelas', models.TextField()),
                ('na_sebelas', models.PositiveSmallIntegerField(choices=[(True, 'Yes'), (False, 'No')], default=True)),
                ('nilai_dua_belas', models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1)], default=4)),
                ('keterangan_dua_belas', models.TextField()),
                ('na_dua_belas', models.PositiveSmallIntegerField(choices=[(True, 'Yes'), (False, 'No')], default=True)),
                ('nilai_tiga_belas', models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1)], default=4)),
                ('keterangan_tiga_belas', models.TextField()),
                ('na_tiga_belas', models.PositiveSmallIntegerField(choices=[(True, 'Yes'), (False, 'No')], default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
