# Generated by Django 3.0.6 on 2020-06-03 01:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_auto_20200521_0106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='keterangan_delapan_belas',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='keterangan_dua_delapan',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='keterangan_dua_dua',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='keterangan_dua_empat',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='keterangan_dua_enam',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='keterangan_dua_lima',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='keterangan_dua_puluh',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='keterangan_dua_satu',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='keterangan_dua_sembilan',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='keterangan_dua_tiga',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='keterangan_dua_tujuh',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='keterangan_empat_belas',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='keterangan_empat_delapan',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='keterangan_empat_dua',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='keterangan_empat_empat',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='keterangan_empat_enam',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='keterangan_empat_lima',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='keterangan_empat_puluh',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='keterangan_empat_satu',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='keterangan_empat_sembilan',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='keterangan_empat_tiga',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='keterangan_empat_tujuh',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='keterangan_enam_belas',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='keterangan_lima_belas',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='keterangan_lima_dua',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='keterangan_lima_empat',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='keterangan_lima_puluh',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='keterangan_lima_satu',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='keterangan_lima_tiga',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='keterangan_sembilan_belas',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='keterangan_tiga_delapan',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='keterangan_tiga_dua',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='keterangan_tiga_empat',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='keterangan_tiga_enam',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='keterangan_tiga_lima',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='keterangan_tiga_puluh',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='keterangan_tiga_satu',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='keterangan_tiga_sembilan',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='keterangan_tiga_tiga',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='keterangan_tiga_tujuh',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='keterangan_tujuh_belas',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='nilai_delapan_belas',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='nilai_dua_delapan',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='nilai_dua_dua',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='nilai_dua_empat',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='nilai_dua_enam',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='nilai_dua_lima',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='nilai_dua_puluh',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='nilai_dua_satu',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='nilai_dua_sembilan',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='nilai_dua_tiga',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='nilai_dua_tujuh',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='nilai_empat_belas',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='nilai_empat_delapan',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='nilai_empat_dua',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='nilai_empat_empat',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='nilai_empat_enam',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='nilai_empat_lima',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='nilai_empat_puluh',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='nilai_empat_satu',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='nilai_empat_sembilan',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='nilai_empat_tiga',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='nilai_empat_tujuh',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='nilai_enam_belas',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='nilai_lima_belas',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='nilai_lima_dua',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='nilai_lima_empat',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='nilai_lima_puluh',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='nilai_lima_satu',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='nilai_lima_tiga',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='nilai_sembilan_belas',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='nilai_tiga_delapan',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='nilai_tiga_dua',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='nilai_tiga_empat',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='nilai_tiga_enam',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='nilai_tiga_lima',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='nilai_tiga_puluh',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='nilai_tiga_satu',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='nilai_tiga_sembilan',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='nilai_tiga_tiga',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='nilai_tiga_tujuh',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='nilai_tujuh_belas',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='rekomendasi_delapan_belas',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='rekomendasi_dua_delapan',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='rekomendasi_dua_dua',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='rekomendasi_dua_empat',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='rekomendasi_dua_enam',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='rekomendasi_dua_lima',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='rekomendasi_dua_puluh',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='rekomendasi_dua_satu',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='rekomendasi_dua_sembilan',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='rekomendasi_dua_tiga',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='rekomendasi_dua_tujuh',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='rekomendasi_empat_belas',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='rekomendasi_empat_delapan',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='rekomendasi_empat_dua',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='rekomendasi_empat_empat',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='rekomendasi_empat_enam',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='rekomendasi_empat_lima',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='rekomendasi_empat_puluh',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='rekomendasi_empat_satu',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='rekomendasi_empat_sembilan',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='rekomendasi_empat_tiga',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='rekomendasi_empat_tujuh',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='rekomendasi_enam_belas',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='rekomendasi_lima_belas',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='rekomendasi_lima_dua',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='rekomendasi_lima_emapt',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='rekomendasi_lima_puluh',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='rekomendasi_lima_satu',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='rekomendasi_lima_tiga',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='rekomendasi_sembilan_belas',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='rekomendasi_tiga_delapan',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='rekomendasi_tiga_dua',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='rekomendasi_tiga_empat',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='rekomendasi_tiga_enam',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='rekomendasi_tiga_lima',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='rekomendasi_tiga_puluh',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='rekomendasi_tiga_satu',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='rekomendasi_tiga_sembilan',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='rekomendasi_tiga_tiga',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='rekomendasi_tiga_tujuh',
        ),
        migrations.RemoveField(
            model_name='questionnairesatu',
            name='rekomendasi_tujuh_belas',
        ),
        migrations.AddField(
            model_name='questionnairesatu',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='QuestionnaireTiga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai_dua_tiga', models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1)], default=4)),
                ('keterangan_dua_tiga', models.TextField(default='Keterangan')),
                ('rekomendasi_dua_tiga', models.TextField(default='Rekomendasi')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionnaireLima',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai_lima_empat', models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1)], default=4)),
                ('keterangan_lima_empat', models.TextField(default='Keterangan')),
                ('rekomendasi_lima_empat', models.TextField(default='Rekomendasi')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionnaireEmpat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai_dua_empat', models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1)], default=4)),
                ('keterangan_dua_empat', models.TextField(default='Keterangan')),
                ('rekomendasi_dua_empat', models.TextField(default='Rekomendasi')),
                ('nilai_dua_lima', models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1)], default=4)),
                ('keterangan_dua_lima', models.TextField(default='Keterangan')),
                ('rekomendasi_dua_lima', models.TextField(default='Rekomendasi')),
                ('nilai_dua_enam', models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1)], default=4)),
                ('keterangan_dua_enam', models.TextField(default='Keterangan')),
                ('rekomendasi_dua_enam', models.TextField(default='Rekomendasi')),
                ('nilai_dua_tujuh', models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1)], default=4)),
                ('keterangan_dua_tujuh', models.TextField(default='Keterangan')),
                ('rekomendasi_dua_tujuh', models.TextField(default='Rekomendasi')),
                ('nilai_dua_delapan', models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1)], default=4)),
                ('keterangan_dua_delapan', models.TextField(default='Keterangan')),
                ('rekomendasi_dua_delapan', models.TextField(default='Rekomendasi')),
                ('nilai_dua_sembilan', models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1)], default=4)),
                ('keterangan_dua_sembilan', models.TextField(default='Keterangan')),
                ('rekomendasi_dua_sembilan', models.TextField(default='Rekomendasi')),
                ('nilai_tiga_puluh', models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1)], default=4)),
                ('keterangan_tiga_puluh', models.TextField(default='Keterangan')),
                ('rekomendasi_tiga_puluh', models.TextField(default='Rekomendasi')),
                ('nilai_tiga_satu', models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1)], default=4)),
                ('keterangan_tiga_satu', models.TextField(default='Keterangan')),
                ('rekomendasi_tiga_satu', models.TextField(default='Rekomendasi')),
                ('nilai_tiga_dua', models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1)], default=4)),
                ('keterangan_tiga_dua', models.TextField(default='Keterangan')),
                ('rekomendasi_tiga_dua', models.TextField(default='Rekomendasi')),
                ('nilai_tiga_tiga', models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1)], default=4)),
                ('keterangan_tiga_tiga', models.TextField(default='Keterangan')),
                ('rekomendasi_tiga_tiga', models.TextField(default='Rekomendasi')),
                ('nilai_tiga_empat', models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1)], default=4)),
                ('keterangan_tiga_empat', models.TextField(default='Keterangan')),
                ('rekomendasi_tiga_empat', models.TextField(default='Rekomendasi')),
                ('nilai_tiga_lima', models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1)], default=4)),
                ('keterangan_tiga_lima', models.TextField(default='Keterangan')),
                ('rekomendasi_tiga_lima', models.TextField(default='Rekomendasi')),
                ('nilai_tiga_enam', models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1)], default=4)),
                ('keterangan_tiga_enam', models.TextField(default='Keterangan')),
                ('rekomendasi_tiga_enam', models.TextField(default='Rekomendasi')),
                ('nilai_tiga_tujuh', models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1)], default=4)),
                ('keterangan_tiga_tujuh', models.TextField(default='Keterangan')),
                ('rekomendasi_tiga_tujuh', models.TextField(default='Rekomendasi')),
                ('nilai_tiga_delapan', models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1)], default=4)),
                ('keterangan_tiga_delapan', models.TextField(default='Keterangan')),
                ('rekomendasi_tiga_delapan', models.TextField(default='Rekomendasi')),
                ('nilai_tiga_sembilan', models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1)], default=4)),
                ('keterangan_tiga_sembilan', models.TextField(default='Keterangan')),
                ('rekomendasi_tiga_sembilan', models.TextField(default='Rekomendasi')),
                ('nilai_empat_puluh', models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1)], default=4)),
                ('keterangan_empat_puluh', models.TextField(default='Keterangan')),
                ('rekomendasi_empat_puluh', models.TextField(default='Rekomendasi')),
                ('nilai_empat_satu', models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1)], default=4)),
                ('keterangan_empat_satu', models.TextField(default='Keterangan')),
                ('rekomendasi_empat_satu', models.TextField(default='Rekomendasi')),
                ('nilai_empat_dua', models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1)], default=4)),
                ('keterangan_empat_dua', models.TextField(default='Keterangan')),
                ('rekomendasi_empat_dua', models.TextField(default='Rekomendasi')),
                ('nilai_empat_tiga', models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1)], default=4)),
                ('keterangan_empat_tiga', models.TextField(default='Keterangan')),
                ('rekomendasi_empat_tiga', models.TextField(default='Rekomendasi')),
                ('nilai_empat_empat', models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1)], default=4)),
                ('keterangan_empat_empat', models.TextField(default='Keterangan')),
                ('rekomendasi_empat_empat', models.TextField(default='Rekomendasi')),
                ('nilai_empat_lima', models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1)], default=4)),
                ('keterangan_empat_lima', models.TextField(default='Keterangan')),
                ('rekomendasi_empat_lima', models.TextField(default='Rekomendasi')),
                ('nilai_empat_enam', models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1)], default=4)),
                ('keterangan_empat_enam', models.TextField(default='Keterangan')),
                ('rekomendasi_empat_enam', models.TextField(default='Rekomendasi')),
                ('nilai_empat_tujuh', models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1)], default=4)),
                ('keterangan_empat_tujuh', models.TextField(default='Keterangan')),
                ('rekomendasi_empat_tujuh', models.TextField(default='Rekomendasi')),
                ('nilai_empat_delapan', models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1)], default=4)),
                ('keterangan_empat_delapan', models.TextField(default='Keterangan')),
                ('rekomendasi_empat_delapan', models.TextField(default='Rekomendasi')),
                ('nilai_empat_sembilan', models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1)], default=4)),
                ('keterangan_empat_sembilan', models.TextField(default='Keterangan')),
                ('rekomendasi_empat_sembilan', models.TextField(default='Rekomendasi')),
                ('nilai_lima_puluh', models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1)], default=4)),
                ('keterangan_lima_puluh', models.TextField(default='Keterangan')),
                ('rekomendasi_lima_puluh', models.TextField(default='Rekomendasi')),
                ('nilai_lima_satu', models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1)], default=4)),
                ('keterangan_lima_satu', models.TextField(default='Keterangan')),
                ('rekomendasi_lima_satu', models.TextField(default='Rekomendasi')),
                ('nilai_lima_dua', models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1)], default=4)),
                ('keterangan_lima_dua', models.TextField(default='Keterangan')),
                ('rekomendasi_lima_dua', models.TextField(default='Rekomendasi')),
                ('nilai_lima_tiga', models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1)], default=4)),
                ('keterangan_lima_tiga', models.TextField(default='Keterangan')),
                ('rekomendasi_lima_tiga', models.TextField(default='Rekomendasi')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionnaireDua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai_empat_belas', models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1)], default=4)),
                ('keterangan_empat_belas', models.TextField(default='Keterangan')),
                ('rekomendasi_empat_belas', models.TextField(default='Rekomendasi')),
                ('nilai_lima_belas', models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1)], default=4)),
                ('keterangan_lima_belas', models.TextField(default='Keterangan')),
                ('rekomendasi_lima_belas', models.TextField(default='Rekomendasi')),
                ('nilai_enam_belas', models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1)], default=4)),
                ('keterangan_enam_belas', models.TextField(default='Keterangan')),
                ('rekomendasi_enam_belas', models.TextField(default='Rekomendasi')),
                ('nilai_tujuh_belas', models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1)], default=4)),
                ('keterangan_tujuh_belas', models.TextField(default='Keterangan')),
                ('rekomendasi_tujuh_belas', models.TextField(default='Rekomendasi')),
                ('nilai_delapan_belas', models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1)], default=4)),
                ('keterangan_delapan_belas', models.TextField(default='Keterangan')),
                ('rekomendasi_delapan_belas', models.TextField(default='Rekomendasi')),
                ('nilai_sembilan_belas', models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1)], default=4)),
                ('keterangan_sembilan_belas', models.TextField(default='Keterangan')),
                ('rekomendasi_sembilan_belas', models.TextField(default='Rekomendasi')),
                ('nilai_dua_puluh', models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1)], default=4)),
                ('keterangan_dua_puluh', models.TextField(default='Keterangan')),
                ('rekomendasi_dua_puluh', models.TextField(default='Rekomendasi')),
                ('nilai_dua_satu', models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1)], default=4)),
                ('keterangan_dua_satu', models.TextField(default='Keterangan')),
                ('rekomendasi_dua_satu', models.TextField(default='Rekomendasi')),
                ('nilai_dua_dua', models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1)], default=4)),
                ('keterangan_dua_dua', models.TextField(default='Keterangan')),
                ('rekomendasi_dua_dua', models.TextField(default='Rekomendasi')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
