# Generated by Django 3.0.6 on 2020-06-04 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200604_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnairesatu',
            name='session_hash',
            field=models.CharField(blank=True, max_length=40, unique=True),
        ),
        migrations.AddField(
            model_name='questionnairesatu',
            name='stage',
            field=models.CharField(default='1', max_length=10),
        ),
    ]
