# Generated by Django 3.0.6 on 2020-06-10 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200605_0400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='session_hash',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='stage',
        ),
    ]
