# Generated by Django 3.0.6 on 2020-06-11 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200611_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='keterangan_proses_metode_dan_prosedur',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='rekomendasi_proses_metode_dan_prosedur',
            field=models.TextField(blank=True),
        ),
    ]
